import Link from 'next/link'
import { createWonder } from '../actions'
import { createClient } from '../../../lib/supabase/server'

export default async function AdminMerveilles() {
  const supabase = await createClient()
  const { data: regions } = supabase ? await supabase.from('niger_regions').select('id,name').order('name') : { data: [] }
  const { data: categories } = supabase ? await supabase.from('niger_categories').select('id,name').order('name') : { data: [] }
  const { data: wonders } = supabase ? await supabase.from('niger_wonders').select('id,name,published,featured,cover_url').order('created_at',{ascending:false}) : { data: [] }
  return <main className="section"><div className="container"><Link className="textlink" href="/admin">← Administration</Link><div className="adminHero"><div><span className="kicker">Merveilles</span><h1>Sites et patrimoines</h1><p className="muted">Crée les fiches touristiques du Niger.</p></div></div><form className="adminForm" action={createWonder}><label>Nom<input required name="name" placeholder="Ex. Grande Mosquée d'Agadez" /></label><div className="formRow"><label>Catégorie<select name="category_id"><option value="">Choisir</option>{(categories||[]).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Région<select name="region_id"><option value="">Choisir</option>{(regions||[]).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label></div><label>Description courte<textarea name="short_description" rows={3}/></label><label>Description complète<textarea name="description" rows={6}/></label><label>Histoire<textarea name="history" rows={5}/></label><label>Pourquoi visiter ?<textarea name="why_visit" rows={4}/></label><div className="formRow"><label>Latitude<input name="latitude" type="number" step="any" /></label><label>Longitude<input name="longitude" type="number" step="any" /></label></div><label>Photo du Niger<input name="cover_url" placeholder="URL d'une photo authentique du Niger" /></label><label>Vidéo<input name="video_url" placeholder="URL vidéo" /></label><label className="check"><input type="checkbox" name="published"/> Publier</label><label className="check"><input type="checkbox" name="featured"/> Mettre en avant</label><button className="btn primary">Enregistrer la merveille</button></form><div className="grid">{(wonders||[]).map(w=><article className="card" key={w.id}><div className="cardbody"><span className="tag">{w.published?'Publié':'Brouillon'}{w.featured?' · ⭐':''}</span><h3>{w.name}</h3></div></article>)}</div></div></main>
}
