import {notFound} from 'next/navigation'
import Link from 'next/link'
import {ArrowLeft,Camera,ExternalLink} from 'lucide-react'
import Header from '../../../components/site/header'
import Footer from '../../../components/site/footer'
import Breadcrumbs from '../../../components/site/breadcrumbs'
import ShareButton from '../../../components/site/share-button'
import {JsonLd} from '../../../components/site/pro-meta'
import {createClient} from '../../../lib/supabase/server'
export const dynamic='force-dynamic'
export default async function MediaDetail({params}:{params:Promise<{id:string}>}){const {id}=await params;const supabase=await createClient();if(!supabase)notFound();const {data:item}=await supabase.from('niger_media').select('*').eq('id',id).eq('published',true).maybeSingle();if(!item)notFound();return <><Header/><main className="page"><div className="container narrowEvent"><Breadcrumbs items={[{label:'Photothèque',href:'/media'},{label:item.title}]}/><JsonLd data={{'@context':'https://schema.org','@type':'ImageObject','name':item.title,'description':item.description,'contentUrl':item.url,'creditText':item.credit,'url':'https://lenigeretsesmerveilles.vercel.app/media/'+id}}/><figure className="proseCard" style={{margin:0}}><img src={item.url} alt={item.title} style={{width:'100%',display:'block',borderRadius:14,maxHeight:700,objectFit:'cover'}}/><figcaption style={{padding:'18px 4px 4px'}}><span className="kicker">Photothèque documentaire</span><h1>{item.title}</h1><p>{item.description||'Image documentaire du Niger.'}</p><p><strong>Crédit :</strong> {item.credit||'Non renseigné'}</p></figcaption></figure><div className="articleShare"><ShareButton title={item.title}/>{item.url&&<a className="proButton proButtonDark" href={item.url} target="_blank" rel="noreferrer"><ExternalLink size={15}/> Source de l’image</a>}</div><Link className="proBack" href="/media"><ArrowLeft size={15}/> Retour à la photothèque</Link></div></main><Footer/></>}