import wonders from '../data/wonders'

export default function Home() {
  const regions = ['Agadez','Diffa','Dosso','Maradi','Niamey','Tahoua','Tillabéri','Zinder']
  return <main>
    <div className="topbar"><div className="container">🇳🇪 Le patrimoine, les cultures et les paysages du Niger réunis dans une seule plateforme.</div></div>
    <nav className="nav"><div className="container navin"><a className="brand" href="#accueil"><span className="brandmark">🇳🇪</span><span>Le Niger et ses Merveilles<small>Explorer • Comprendre • Préserver</small></span></a><div className="links"><a href="#explorer">Explorer</a><a href="#merveilles">Merveilles</a><a href="#culture">Culture</a><a href="#carte">Carte</a><a href="#ia">IA</a></div><a className="navbtn" href="#merveilles">Commencer</a></div></nav>
    <section id="accueil" className="hero"><div className="heroContent container"><span className="eyebrow">✦ Plateforme culturelle & touristique</span><h1>Découvrez le Niger autrement.</h1><p>Une expérience numérique pour explorer les régions, les paysages, le patrimoine, les cultures, les traditions et les merveilles du Niger.</p><div className="actions"><a className="btn primary" href="#merveilles">Explorer les merveilles →</a><a className="btn ghost" href="#explorer">Voir les régions</a></div></div></section>
    <div className="container"><div className="stats"><div className="stat"><strong>8</strong><span>Régions à explorer</span></div><div className="stat"><strong>∞</strong><span>Histoires à découvrir</span></div><div className="stat"><strong>🇳🇪</strong><span>Une identité plurielle</span></div><div className="stat"><strong>24/7</strong><span>Guide numérique</span></div></div></div>
    <section id="merveilles" className="section"><div className="container"><div className="sectionHead"><div><div className="kicker">À découvrir</div><h2>Les merveilles du Niger</h2></div><p className="muted">Des destinations sélectionnées pour commencer l’exploration.</p></div><div className="grid">{wonders.map(w=><article className="card" key={w.name}><div className="cardimg" style={{backgroundImage:`url(${w.image})`}}/><div className="cardbody"><span className="tag">{w.type}</span><h3>{w.name}</h3><p>{w.text}</p></div></article>)}</div></div></section>
    <section id="explorer" className="section explorer"><div className="container"><div className="sectionHead"><div><div className="kicker">Explorer</div><h2>Les 8 régions</h2></div><p className="muted">Chaque région aura son espace dédié.</p></div><div className="regionGrid">{regions.map((r,i)=><div className="region" key={r}><b>{r}</b><span>{i===4?'Capitale nationale':'Découvrir la région'} →</span></div>)}</div></div></section>
    <section id="culture" className="section"><div className="container"><div className="feature"><div className="featureBox"><div><span className="tag">Culture & patrimoine</span><h3>Une diversité à raconter.</h3><p>Traditions, artisanat, gastronomie, musique, histoire et savoir-faire.</p></div></div><div className="listbox"><div className="kicker">À explorer bientôt</div><div className="listitem"><b>👥 Peuples & traditions</b><span className="muted">Histoire, langues, vêtements, pratiques et savoir-faire.</span></div><div className="listitem"><b>🍲 Gastronomie</b><span className="muted">Découvrez les plats et les traditions culinaires.</span></div><div className="listitem"><b>🎭 Événements</b><span className="muted">Festivals, rencontres et rendez-vous culturels.</span></div><div className="listitem"><b>📸 Contributions</b><span className="muted">Les visiteurs pourront proposer leurs découvertes.</span></div></div></div></div></section>
    <section id="carte" className="section"><div className="container"><div className="ai"><div><div className="kicker">Carte interactive</div><h2>Le Niger, sur une seule carte.</h2><p className="muted">La prochaine étape intégrera les régions, sites, patrimoines et événements avec une carte interactive.</p></div><a className="btn primary" href="#explorer">Explorer</a></div></div></section>
    <section id="ia" className="section"><div className="container"><div className="ai"><div><div className="kicker">Assistant intelligent</div><h2>🤖 Assistant Niger</h2><p className="muted">Posez une question sur une région, un patrimoine, une culture ou un itinéraire. L’assistant sera connecté à la base documentaire de la plateforme.</p></div><button type="button">IA bientôt disponible</button></div></div></section>
    <footer className="footer"><div className="container"><div className="footergrid"><div><div className="brand"><span className="brandmark">🇳🇪</span><span>Le Niger et ses Merveilles<small>Explorer • Comprendre • Préserver</small></span></div><p className="muted">Une plateforme numérique dédiée à la découverte et à la valorisation du Niger.</p></div><div><h4>Explorer</h4><a href="#merveilles">Merveilles</a><a href="#explorer">Régions</a><a href="#culture">Culture</a></div><div><h4>Plateforme</h4><a href="#carte">Carte</a><a href="#ia">Assistant IA</a><a href="#accueil">Accueil</a></div><div><h4>Participer</h4><a href="#culture">Partager une découverte</a><a href="#culture">Devenir contributeur</a></div></div><div className="copy">© 2026 Le Niger et ses Merveilles — Projet numérique.</div></div></footer>
  </main>
}
