import Link from 'next/link'
import Header from '../components/site/header'
import Footer from '../components/site/footer'
import wonders from '../data/wonders'
import { regions } from '../data/regions'

export default function Home() {
  return <><Header/><main>
    <section className="hero"><div className="heroContent container"><span className="eyebrow">✦ Plateforme culturelle & touristique</span><h1>Découvrez le Niger autrement.</h1><p>Explorez les régions, paysages, patrimoines, cultures, traditions et merveilles du Niger dans une expérience numérique moderne.</p><div className="actions"><Link className="btn primary" href="/merveilles">Explorer les merveilles →</Link><Link className="btn ghost" href="/regions">Voir les régions</Link></div></div></section>
    <div className="container"><div className="stats"><div className="stat"><strong>8</strong><span>Régions à explorer</span></div><div className="stat"><strong>{wonders.length}</strong><span>Découvertes de départ</span></div><div className="stat"><strong>🇳🇪</strong><span>Une identité plurielle</span></div><div className="stat"><strong>24/7</strong><span>Guide numérique</span></div></div></div>
    <section className="section"><div className="container"><div className="sectionHead"><div><div className="kicker">À découvrir</div><h2>Les merveilles du Niger</h2></div><Link className="textlink" href="/merveilles">Tout voir →</Link></div><div className="grid">{wonders.map(w=><article className="card" key={w.name}><div className="cardimg" style={{backgroundImage:`url(${w.image})`}}/><div className="cardbody"><span className="tag">{w.type}</span><h3>{w.name}</h3><p>{w.text}</p></div></article>)}</div></div></section>
    <section className="section explorer"><div className="container"><div className="sectionHead"><div><div className="kicker">Explorer</div><h2>Les 8 régions</h2></div><Link className="textlink light" href="/regions">Ouvrir l’explorateur →</Link></div><div className="regionGrid">{regions.map(r=><Link className="region" href={`/regions/${r.slug}`} key={r.slug}><b>{r.name}</b><span>Découvrir la région →</span></Link>)}</div></div></section>
    <section className="section"><div className="container"><div className="feature"><div className="featureBox"><div><span className="tag">Culture & patrimoine</span><h3>Une diversité à raconter.</h3><p>Traditions, artisanat, gastronomie, musique, histoire et savoir-faire.</p></div></div><div className="listbox"><div className="kicker">À explorer</div><div className="listitem"><b>👥 Peuples & traditions</b><span className="muted">Histoires, langues, vêtements et savoir-faire.</span></div><div className="listitem"><b>🍲 Gastronomie</b><span className="muted">Découvrez les plats et traditions culinaires.</span></div><div className="listitem"><b>🎭 Événements</b><span className="muted">Festivals et rendez-vous culturels.</span></div><div className="listitem"><b>📸 Contributions</b><span className="muted">Partagez vos découvertes avec la communauté.</span></div></div></div></div></section>
    <section className="section"><div className="container"><div className="ai"><div><div className="kicker">Carte & assistant</div><h2>Le Niger, sur une seule plateforme.</h2><p className="muted">Accédez aux régions, aux lieux et aux contenus culturels. La carte interactive et l’assistant intelligent sont prêts à évoluer avec la base documentaire.</p></div><div className="actions"><Link className="btn primary" href="/carte">Voir la carte</Link><Link className="btn darkbtn" href="/contribution">Contribuer</Link></div></div></div></section>
  </main><Footer/></>
}
